# Generated by Django 4.2.23 on 2025-09-06 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('track_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('artists', models.CharField(max_length=255)),
                ('album_name', models.CharField(blank=True, max_length=255, null=True)),
                ('track_name', models.CharField(max_length=255)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('explicit', models.BooleanField(blank=True, null=True)),
                ('danceability', models.FloatField(blank=True, null=True)),
                ('energy', models.FloatField(blank=True, null=True)),
                ('key', models.CharField(blank=True, max_length=10, null=True)),
                ('loudness', models.FloatField(blank=True, null=True)),
                ('mode', models.IntegerField(blank=True, null=True)),
                ('speechiness', models.FloatField(blank=True, null=True)),
                ('acousticness', models.FloatField(blank=True, null=True)),
                ('instrumentalness', models.FloatField(blank=True, null=True)),
                ('liveness', models.FloatField(blank=True, null=True)),
                ('valence', models.FloatField(blank=True, null=True)),
                ('tempo', models.FloatField(blank=True, null=True)),
                ('time_signature', models.IntegerField(blank=True, null=True)),
                ('track_genre', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'track',
            },
        ),
        migrations.CreateModel(
            name='ProcessedTrack',
            fields=[
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nexttrack.track')),
                ('popularity_scaled', models.FloatField(blank=True, null=True)),
                ('duration_ms_scaled', models.FloatField(blank=True, null=True)),
                ('danceability_scaled', models.FloatField(blank=True, null=True)),
                ('energy_scaled', models.FloatField(blank=True, null=True)),
                ('loudness_scaled', models.FloatField(blank=True, null=True)),
                ('speechiness_scaled', models.FloatField(blank=True, null=True)),
                ('acousticness_scaled', models.FloatField(blank=True, null=True)),
                ('instrumentalness_scaled', models.FloatField(blank=True, null=True)),
                ('liveness_scaled', models.FloatField(blank=True, null=True)),
                ('valence_scaled', models.FloatField(blank=True, null=True)),
                ('tempo_scaled', models.FloatField(blank=True, null=True)),
                ('key_encoded', models.IntegerField(blank=True, null=True)),
                ('mode_encoded', models.IntegerField(blank=True, null=True)),
                ('time_signature_encoded', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'processed_track',
            },
        ),
        migrations.CreateModel(
            name='TrackEmbedding',
            fields=[
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nexttrack.track')),
                ('embedding_0', models.FloatField(blank=True, null=True)),
                ('embedding_1', models.FloatField(blank=True, null=True)),
                ('embedding_2', models.FloatField(blank=True, null=True)),
                ('embedding_3', models.FloatField(blank=True, null=True)),
                ('embedding_4', models.FloatField(blank=True, null=True)),
                ('embedding_5', models.FloatField(blank=True, null=True)),
                ('embedding_6', models.FloatField(blank=True, null=True)),
                ('embedding_7', models.FloatField(blank=True, null=True)),
                ('embedding_8', models.FloatField(blank=True, null=True)),
                ('embedding_9', models.FloatField(blank=True, null=True)),
                ('embedding_10', models.FloatField(blank=True, null=True)),
                ('embedding_11', models.FloatField(blank=True, null=True)),
                ('embedding_12', models.FloatField(blank=True, null=True)),
                ('embedding_13', models.FloatField(blank=True, null=True)),
                ('embedding_14', models.FloatField(blank=True, null=True)),
                ('embedding_15', models.FloatField(blank=True, null=True)),
                ('embedding_16', models.FloatField(blank=True, null=True)),
                ('embedding_17', models.FloatField(blank=True, null=True)),
                ('embedding_18', models.FloatField(blank=True, null=True)),
                ('embedding_19', models.FloatField(blank=True, null=True)),
                ('embedding_20', models.FloatField(blank=True, null=True)),
                ('embedding_21', models.FloatField(blank=True, null=True)),
                ('embedding_22', models.FloatField(blank=True, null=True)),
                ('embedding_23', models.FloatField(blank=True, null=True)),
                ('embedding_24', models.FloatField(blank=True, null=True)),
                ('embedding_25', models.FloatField(blank=True, null=True)),
                ('embedding_26', models.FloatField(blank=True, null=True)),
                ('embedding_27', models.FloatField(blank=True, null=True)),
                ('embedding_28', models.FloatField(blank=True, null=True)),
                ('embedding_29', models.FloatField(blank=True, null=True)),
                ('embedding_30', models.FloatField(blank=True, null=True)),
                ('embedding_31', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'track_embedding',
            },
        ),
    ]
