# Generated by Django 4.2.23 on 2025-09-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexttrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artists',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
