# Generated by Django 4.2.23 on 2025-09-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexttrack', '0003_alter_track_track_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
